import * as React from "react";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Grid";
import Link from "@mui/material/Link";
import Box from "@mui/material/Box";
import FeaturedPost from "@/components/Home/Blogs/FeaturedPost";

const mainFeaturedPost = {
  title: "Unlock the Power of IoT Data Integration",
  description:
    "Discover how our platform enhances decision-making by integrating data from diverse IoT networks into a single, unified interface. Explore the transformative impact on businesses and smart cities.",
  image: "/blogs/featured-blog.jpg",
  imageText: "IoT Data Integration",
  linkText: "Continue reading…",
};

const featuredPosts = [
  {
    title: "Streamlining IoT Device Management",
    date: "Nov 12",
    description:
      "Learn how our platform simplifies the management of IoT devices, allowing seamless connectivity and real-time monitoring across various networks.",
    image: "/blogs/featured-blog-1.jpg",
    imageLabel: "IoT Device Management",
  },
  {
    title: "Transforming Data into Insights",
    date: "Nov 11",
    description:
      "Explore the advanced analytics tools our platform offers, helping you turn raw IoT data into actionable insights that drive smarter decisions.",
    image: "/blogs/featured-blog-2.jpg",
    imageLabel: "Data Analytics",
  },
  {
    title: "Securing IoT Networks for the Future",
    date: "Oct 25",
    description:
      "Discover our cutting-edge security features designed to protect IoT networks from evolving cyber threats and ensure data integrity.",
    image: "/blogs/featured-blog-3.jpeg",
    imageLabel: "IoT Security",
  },
  {
    title: "Enhancing User Experience with IoT Automation",
    date: "Oct 18",
    description:
      "See how automation within our platform can enhance user experience by enabling predictive maintenance, energy management, and more.",
    image: "/blogs/featured-blog-4.avif",
    imageLabel: "IoT Automation",
  },
  {
    title: "Harnessing the Power of Big Data in IoT",
    date: "Oct 10",
    description:
      "Learn how our platform handles big data generated by IoT devices and provides scalable solutions for data storage and processing.",
    image: "/blogs/featured-blog-5.avif",
    imageLabel: "Big Data IoT",
  },
  {
    title: "Real-Time Monitoring and Alerts",
    date: "Sep 30",
    description:
      "Understand the importance of real-time monitoring in IoT systems and how our platform delivers instant alerts for critical conditions.",
    image: "/blogs/featured-blog-6.avif",
    imageLabel: "Real-Time Monitoring",
  },
  {
    title: "Optimizing Industrial IoT (IIoT) Systems",
    date: "Sep 22",
    description:
      "Explore our specialized features for industrial IoT, including tools for monitoring, controlling, and optimizing industrial processes.",
    image: "/blogs/featured-blog-7.jpg",
    imageLabel: "Industrial IoT",
  },
  {
    title: "Seamless API Integration for IoT Applications",
    date: "Sep 15",
    description:
      "Discover how our platform’s API integration enables seamless connectivity between IoT devices and third-party applications, fostering innovation.",
    image: "/blogs/featured-blog-8.jpg",
    imageLabel: "API Integration",
  },
  {
    title: "Supporting Smart City Initiatives",
    date: "Sep 8",
    description:
      "Learn how our platform supports smart city initiatives by enabling the integration of various IoT networks for efficient urban management.",
    image: "/blogs/featured-blog-9.avif",
    imageLabel: "Smart City IoT",
  },
  {
    title: "Boosting Agricultural Efficiency with IoT",
    date: "Aug 30",
    description:
      "See how IoT technology on our platform boosts agricultural efficiency by providing real-time data on soil conditions, weather patterns, and crop health.",
    image: "/blogs/featured-blog-10.jpg",
    imageLabel: "Agriculture IoT",
  },
];

export default function MainFeaturedPost() {
  return (
    <>
      <Paper
        sx={{
          position: "relative",
          backgroundColor: "grey.800",
          color: "#fff",
          mb: 4,
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
          backgroundPosition: "center",
          backgroundImage: `url(${mainFeaturedPost.image})`,
          height: 200,
        }}
      >
        {/* Increase the priority of the hero background image */}
        {
          <img
            style={{ display: "none" }}
            src={mainFeaturedPost.image}
            alt={mainFeaturedPost.imageText}
          />
        }
        <Box
          sx={{
            position: "absolute",
            top: 0,
            bottom: 0,
            right: 0,
            left: 0,
            backgroundColor: "rgba(0,0,0,.3)",
          }}
        />
        <Grid container>
          <Grid item md={6}>
            <Box
              sx={{
                position: "relative",
                p: { xs: 3, md: 6 },
                pr: { md: 0 },
              }}
            >
              <Typography
                component="h1"
                variant="h3"
                color="inherit"
                gutterBottom
              >
                {mainFeaturedPost.title}
              </Typography>
              <Typography variant="h5" color="inherit" paragraph>
                {mainFeaturedPost.description}
              </Typography>
              <Link variant="subtitle1" href="#">
                {mainFeaturedPost.linkText}
              </Link>
            </Box>
          </Grid>
        </Grid>
      </Paper>
      <Grid container spacing={4}>
        {featuredPosts.map((post) => (
          <FeaturedPost key={post.title} post={post} />
        ))}
      </Grid>
    </>
  );
}
